from sqlalchemy.orm import Session
from models.product import Product


def seed_products(db: Session):
    """Idempotent seeding: insert products that don't exist, skip those that do.

    Uses product id as the uniqueness key. Existing cart/order/payment records
    are never touched. Existing products are never overwritten.
    """
    existing_ids = {pid for (pid,) in db.query(Product.id).all()}

    products = [
        # ── HEADPHONES (8) ──────────────────────────────────────────────
        Product(
            id="sony-wh-ch520",
            name="Sony WH-CH520",
            description="Wireless on-ear headphones with up to 50-hour battery life and clear sound quality.",
            price=4490.00,
            currency="INR",
            category="headphones",
            attributes={
                "brand": "Sony",
                "type": "on-ear",
                "battery_life_hours": 50,
                "noise_cancellation": False,
                "wireless": True,
                "bluetooth_version": "5.0",
                "weight_grams": 147,
            },
            stock_quantity=25,
        ),
        Product(
            id="jbl-tune-510bt",
            name="JBL Tune 510BT",
            description="On-ear wireless headphones with JBL Pure Bass sound and 40-hour battery.",
            price=3999.00,
            currency="INR",
            category="headphones",
            attributes={
                "brand": "JBL",
                "type": "on-ear",
                "battery_life_hours": 40,
                "noise_cancellation": False,
                "wireless": True,
                "bluetooth_version": "5.0",
                "weight_grams": 160,
            },
            stock_quantity=30,
        ),
        Product(
            id="boat-rockerz-450",
            name="boAt Rockerz 450",
            description="Over-ear wireless headphones with 15-hour playback and ergonomic design.",
            price=1499.00,
            currency="INR",
            category="headphones",
            attributes={
                "brand": "boAt",
                "type": "over-ear",
                "battery_life_hours": 15,
                "noise_cancellation": False,
                "wireless": True,
                "bluetooth_version": "4.2",
                "weight_grams": 230,
            },
            stock_quantity=50,
        ),
        Product(
            id="sony-wh-1000xm4",
            name="Sony WH-1000XM4",
            description="Industry-leading noise cancelling headphones with 30-hour battery and premium sound.",
            price=19990.00,
            currency="INR",
            category="headphones",
            attributes={
                "brand": "Sony",
                "type": "over-ear",
                "battery_life_hours": 30,
                "noise_cancellation": True,
                "wireless": True,
                "bluetooth_version": "5.0",
                "weight_grams": 254,
            },
            stock_quantity=10,
        ),
        Product(
            id="sony-wh-1000xm5",
            name="Sony WH-1000XM5",
            description="Flagship noise cancelling headphones with auto NC optimizer, 30-hour battery, and multipoint connection.",
            price=26990.00,
            currency="INR",
            category="headphones",
            attributes={
                "brand": "Sony",
                "type": "over-ear",
                "battery_life_hours": 30,
                "noise_cancellation": True,
                "wireless": True,
                "bluetooth_version": "5.2",
                "weight_grams": 250,
            },
            stock_quantity=8,
        ),
        Product(
            id="bose-700",
            name="Bose 700",
            description="Premium noise cancelling headphones with 11 levels of ANC and crystalline audio.",
            price=23900.00,
            currency="INR",
            category="headphones",
            attributes={
                "brand": "Bose",
                "type": "over-ear",
                "battery_life_hours": 20,
                "noise_cancellation": True,
                "wireless": True,
                "bluetooth_version": "5.0",
                "weight_grams": 254,
            },
            stock_quantity=6,
        ),
        Product(
            id="jbl-live-660nc",
            name="JBL Live 660NC",
            description="Over-ear wireless headphones with adaptive noise cancellation and 50-hour battery life.",
            price=12999.00,
            currency="INR",
            category="headphones",
            attributes={
                "brand": "JBL",
                "type": "over-ear",
                "battery_life_hours": 50,
                "noise_cancellation": True,
                "wireless": True,
                "bluetooth_version": "5.2",
                "weight_grams": 252,
            },
            stock_quantity=12,
        ),
        Product(
            id="audio-technica-ath-m50x",
            name="Audio-Technica ATH-M50x",
            description="Professional studio monitor headphones with detailed audio and replaceable earpads.",
            price=14990.00,
            currency="INR",
            category="headphones",
            attributes={
                "brand": "Audio-Technica",
                "type": "over-ear",
                "battery_life_hours": 0,
                "noise_cancellation": False,
                "wireless": False,
                "bluetooth_version": None,
                "weight_grams": 285,
            },
            stock_quantity=7,
        ),

        # ── EARBUDS (8) ─────────────────────────────────────────────────
        Product(
            id="sony-wf-c500",
            name="Sony WF-C500",
            description="True wireless earbuds with digital sound quality and lightweight design.",
            price=4490.00,
            currency="INR",
            category="earbuds",
            attributes={
                "brand": "Sony",
                "type": "tws",
                "battery_life_hours": 10,
                "noise_cancellation": False,
                "wireless": True,
                "bluetooth_version": "5.0",
                "water_resistant": True,
            },
            stock_quantity=20,
        ),
        Product(
            id="jbl-wave-200tws",
            name="JBL Wave 200TWS",
            description="True wireless earbuds with deep bass and 20 hours of combined battery.",
            price=3299.00,
            currency="INR",
            category="earbuds",
            attributes={
                "brand": "JBL",
                "type": "tws",
                "battery_life_hours": 20,
                "noise_cancellation": False,
                "wireless": True,
                "bluetooth_version": "5.0",
                "water_resistant": False,
            },
            stock_quantity=35,
        ),
        Product(
            id="boat-airdopes-141",
            name="boAt Airdopes 141",
            description="TWS earbuds with 42-hour total playback and ENx noise cancellation.",
            price=1099.00,
            currency="INR",
            category="earbuds",
            attributes={
                "brand": "boAt",
                "type": "tws",
                "battery_life_hours": 42,
                "noise_cancellation": True,
                "wireless": True,
                "bluetooth_version": "5.1",
                "water_resistant": True,
            },
            stock_quantity=100,
        ),
        Product(
            id="oneplus-buds-z2",
            name="OnePlus Buds Z2",
            description="True wireless earbuds with 38-hour total battery and ANC support.",
            price=3999.00,
            currency="INR",
            category="earbuds",
            attributes={
                "brand": "OnePlus",
                "type": "tws",
                "battery_life_hours": 38,
                "noise_cancellation": True,
                "wireless": True,
                "bluetooth_version": "5.2",
                "water_resistant": True,
            },
            stock_quantity=28,
        ),
        Product(
            id="realme-buds-air-3",
            name="Realme Buds Air 3",
            description="TWS earbuds with 30-hour total battery and active noise cancellation.",
            price=2999.00,
            currency="INR",
            category="earbuds",
            attributes={
                "brand": "Realme",
                "type": "tws",
                "battery_life_hours": 30,
                "noise_cancellation": True,
                "wireless": True,
                "bluetooth_version": "5.2",
                "water_resistant": True,
            },
            stock_quantity=40,
        ),
        Product(
            id="jbl-live-pro-2",
            name="JBL Live Pro 2",
            description="Premium TWS earbuds with 40-hour total battery, ANC, and Hi-Res audio.",
            price=7999.00,
            currency="INR",
            category="earbuds",
            attributes={
                "brand": "JBL",
                "type": "tws",
                "battery_life_hours": 40,
                "noise_cancellation": True,
                "wireless": True,
                "bluetooth_version": "5.2",
                "water_resistant": True,
            },
            stock_quantity=15,
        ),
        Product(
            id="sony-wf-1000xm5",
            name="Sony WF-1000XM5",
            description="Flagship TWS earbuds with industry-leading noise cancellation and Hi-Res Audio Wireless.",
            price=24990.00,
            currency="INR",
            category="earbuds",
            attributes={
                "brand": "Sony",
                "type": "tws",
                "battery_life_hours": 24,
                "noise_cancellation": True,
                "wireless": True,
                "bluetooth_version": "5.3",
                "water_resistant": True,
            },
            stock_quantity=5,
        ),
        Product(
            id="samsung-galaxy-buds2-pro",
            name="Samsung Galaxy Buds2 Pro",
            description="Premium TWS earbuds with 24-bit Hi-Fi sound, ANC, and seamless Galaxy ecosystem integration.",
            price=11999.00,
            currency="INR",
            category="earbuds",
            attributes={
                "brand": "Samsung",
                "type": "tws",
                "battery_life_hours": 29,
                "noise_cancellation": True,
                "wireless": True,
                "bluetooth_version": "5.3",
                "water_resistant": True,
            },
            stock_quantity=14,
        ),

        # ── WIRED EARPHONES (2) ─────────────────────────────────────────
        Product(
            id="boat-bassheads-100",
            name="boAt BassHeads 100",
            description="Wired in-ear earphones with tangle-free cable and HD sound.",
            price=399.00,
            currency="INR",
            category="wired-earphones",
            attributes={
                "brand": "boAt",
                "type": "in-ear",
                "wired": True,
                "connector": "3.5mm",
                "microphone": True,
                "cable_length_m": 1.2,
            },
            stock_quantity=200,
        ),
        Product(
            id="jbl-c100si",
            name="JBL C100SI",
            description="Wired in-ear earphones with JBL signature sound and comfortable fit.",
            price=599.00,
            currency="INR",
            category="wired-earphones",
            attributes={
                "brand": "JBL",
                "type": "in-ear",
                "wired": True,
                "connector": "3.5mm",
                "microphone": True,
                "cable_length_m": 1.2,
            },
            stock_quantity=150,
        ),
        Product(
            id="sennheiser-cx-80s",
            name="Sennheiser CX 80S",
            description="Premium wired in-ear earphones with dynamic drivers and rich, balanced sound.",
            price=1499.00,
            currency="INR",
            category="wired-earphones",
            attributes={
                "brand": "Sennheiser",
                "type": "in-ear",
                "wired": True,
                "connector": "3.5mm",
                "microphone": True,
                "cable_length_m": 1.2,
            },
            stock_quantity=120,
        ),
        Product(
            id="audio-technica-ath-cks50tw",
            name="Audio-Technica ATH-CK350",
            description="Wired in-ear earphones with high-resolution drivers and lightweight aluminium housing.",
            price=2299.00,
            currency="INR",
            category="wired-earphones",
            attributes={
                "brand": "Audio-Technica",
                "type": "in-ear",
                "wired": True,
                "connector": "3.5mm",
                "microphone": True,
                "cable_length_m": 1.2,
            },
            stock_quantity=80,
        ),
        Product(
            id="fiio-fd1",
            name="FiiO FD1",
            description="Audiophile-grade dynamic wired earphone with replaceable cable and detachable MMCX connectors.",
            price=2999.00,
            currency="INR",
            category="wired-earphones",
            attributes={
                "brand": "FiiO",
                "type": "in-ear",
                "wired": True,
                "connector": "MMCX",
                "microphone": False,
                "cable_length_m": 1.2,
            },
            stock_quantity=60,
        ),

        # ── LAPTOPS (12) ────────────────────────────────────────────────
        Product(
            id="hp-chromebook-14",
            name="HP Chromebook 14",
            description="Lightweight Chromebook with 14-inch HD display, ideal for browsing and cloud-based work.",
            price=22999.00,
            currency="INR",
            category="laptops",
            attributes={
                "brand": "HP",
                "processor": "Intel Celeron N4020",
                "ram_gb": 4,
                "storage_gb": 64,
                "storage_type": "eMMC",
                "gpu": "Intel UHD Graphics 600",
                "operating_system": "Chrome OS",
                "display_size_inches": 14.0,
                "battery_life_hours": 10,
                "weight_kg": 1.46,
            },
            stock_quantity=18,
        ),
        Product(
            id="lenovo-ideapad-slim-3",
            name="Lenovo IdeaPad Slim 3",
            description="Affordable everyday laptop with AMD Ryzen 3 processor, 15.6-inch display, and fast SSD.",
            price=32999.00,
            currency="INR",
            category="laptops",
            attributes={
                "brand": "Lenovo",
                "processor": "AMD Ryzen 3 7320U",
                "ram_gb": 8,
                "storage_gb": 256,
                "storage_type": "SSD",
                "gpu": "AMD Radeon Graphics",
                "operating_system": "Windows 11",
                "display_size_inches": 15.6,
                "battery_life_hours": 7,
                "weight_kg": 1.63,
            },
            stock_quantity=22,
        ),
        Product(
            id="acer-aspire-5",
            name="Acer Aspire 5",
            description="Slim and stylish laptop with 13th Gen Intel Core i5, 8GB RAM, and 512GB SSD.",
            price=44999.00,
            currency="INR",
            category="laptops",
            attributes={
                "brand": "Acer",
                "processor": "Intel Core i5-1335U",
                "ram_gb": 8,
                "storage_gb": 512,
                "storage_type": "SSD",
                "gpu": "Intel Iris Xe Graphics",
                "operating_system": "Windows 11",
                "display_size_inches": 15.6,
                "battery_life_hours": 8,
                "weight_kg": 1.78,
            },
            stock_quantity=15,
        ),
        Product(
            id="hp-pavilion-15",
            name="HP Pavilion 15",
            description="Mid-range laptop with Ryzen 5 processor, backlit keyboard, and full HD display.",
            price=52999.00,
            currency="INR",
            category="laptops",
            attributes={
                "brand": "HP",
                "processor": "AMD Ryzen 5 7530U",
                "ram_gb": 16,
                "storage_gb": 512,
                "storage_type": "SSD",
                "gpu": "AMD Radeon Graphics",
                "operating_system": "Windows 11",
                "display_size_inches": 15.6,
                "battery_life_hours": 8,
                "weight_kg": 1.74,
            },
            stock_quantity=12,
        ),
        Product(
            id="dell-inspiron-15",
            name="Dell Inspiron 15",
            description="Reliable all-rounder laptop with 13th Gen Intel Core i5, 16GB RAM, and 512GB SSD.",
            price=55999.00,
            currency="INR",
            category="laptops",
            attributes={
                "brand": "Dell",
                "processor": "Intel Core i5-1335U",
                "ram_gb": 16,
                "storage_gb": 512,
                "storage_type": "SSD",
                "gpu": "Intel Iris Xe Graphics",
                "operating_system": "Windows 11",
                "display_size_inches": 15.6,
                "battery_life_hours": 7,
                "weight_kg": 1.65,
            },
            stock_quantity=10,
        ),
        Product(
            id="asus-vivobook-15",
            name="ASUS VivoBook 15",
            description="Compact and lightweight laptop with OLED display option, fast charging, and fingerprint sensor.",
            price=49999.00,
            currency="INR",
            category="laptops",
            attributes={
                "brand": "ASUS",
                "processor": "AMD Ryzen 5 5600H",
                "ram_gb": 16,
                "storage_gb": 512,
                "storage_type": "SSD",
                "gpu": "NVIDIA GeForce GTX 1650",
                "operating_system": "Windows 11",
                "display_size_inches": 15.6,
                "battery_life_hours": 8,
                "weight_kg": 1.70,
            },
            stock_quantity=14,
        ),
        Product(
            id="macbook-air-m1",
            name="Apple MacBook Air M1",
            description="Ultra-thin fanless laptop with Apple M1 chip, 13.3-inch Retina display, and all-day battery.",
            price=74900.00,
            currency="INR",
            category="laptops",
            attributes={
                "brand": "Apple",
                "processor": "Apple M1",
                "ram_gb": 8,
                "storage_gb": 256,
                "storage_type": "SSD",
                "gpu": "Apple 7-core GPU",
                "operating_system": "macOS",
                "display_size_inches": 13.3,
                "battery_life_hours": 15,
                "weight_kg": 1.29,
            },
            stock_quantity=6,
        ),
        Product(
            id="lenovo-ideapad-slim-5",
            name="Lenovo IdeaPad Slim 5",
            description="Premium slim laptop with OLED display, AMD Ryzen 7, and rapid charge support.",
            price=64999.00,
            currency="INR",
            category="laptops",
            attributes={
                "brand": "Lenovo",
                "processor": "AMD Ryzen 7 7730U",
                "ram_gb": 16,
                "storage_gb": 512,
                "storage_type": "SSD",
                "gpu": "AMD Radeon Graphics",
                "operating_system": "Windows 11",
                "display_size_inches": 16.0,
                "battery_life_hours": 10,
                "weight_kg": 1.90,
            },
            stock_quantity=8,
        ),
        Product(
            id="hp-envy-16",
            name="HP Envy 16",
            description="Creator laptop with 16-inch 2.5K display, Intel Core i7, and RTX 4060 GPU.",
            price=124999.00,
            currency="INR",
            category="laptops",
            attributes={
                "brand": "HP",
                "processor": "Intel Core i7-13700H",
                "ram_gb": 16,
                "storage_gb": 1024,
                "storage_type": "SSD",
                "gpu": "NVIDIA GeForce RTX 4060",
                "operating_system": "Windows 11",
                "display_size_inches": 16.0,
                "battery_life_hours": 6,
                "weight_kg": 2.27,
            },
            stock_quantity=4,
        ),
        Product(
            id="dell-inspiron-16",
            name="Dell Inspiron 16 Plus",
            description="Powerhouse laptop with 16-inch 2.5K display, Intel Core i7, and dedicated NVIDIA GPU.",
            price=89999.00,
            currency="INR",
            category="laptops",
            attributes={
                "brand": "Dell",
                "processor": "Intel Core i7-13700H",
                "ram_gb": 16,
                "storage_gb": 1024,
                "storage_type": "SSD",
                "gpu": "NVIDIA GeForce RTX 4050",
                "operating_system": "Windows 11",
                "display_size_inches": 16.0,
                "battery_life_hours": 7,
                "weight_kg": 2.05,
            },
            stock_quantity=5,
        ),
        Product(
            id="asus-rog-strix-g16",
            name="ASUS ROG Strix G16",
            description="Gaming laptop with 16-inch 165Hz display, Intel Core i9, and RTX 4070 GPU.",
            price=149999.00,
            currency="INR",
            category="laptops",
            attributes={
                "brand": "ASUS",
                "processor": "Intel Core i9-14900HX",
                "ram_gb": 32,
                "storage_gb": 1024,
                "storage_type": "SSD",
                "gpu": "NVIDIA GeForce RTX 4070",
                "operating_system": "Windows 11",
                "display_size_inches": 16.0,
                "battery_life_hours": 5,
                "weight_kg": 2.50,
            },
            stock_quantity=3,
        ),
        Product(
            id="macbook-pro-14-m3",
            name="Apple MacBook Pro 14 M3",
            description="Pro-grade laptop with Apple M3 chip, 14.2-inch Liquid Retina XDR display, and up to 18-hour battery.",
            price=169900.00,
            currency="INR",
            category="laptops",
            attributes={
                "brand": "Apple",
                "processor": "Apple M3",
                "ram_gb": 18,
                "storage_gb": 512,
                "storage_type": "SSD",
                "gpu": "Apple 10-core GPU",
                "operating_system": "macOS",
                "display_size_inches": 14.2,
                "battery_life_hours": 18,
                "weight_kg": 1.55,
            },
            stock_quantity=3,
        ),

        Product(
            id="asus-zenbook-14-oled",
            name="ASUS Zenbook 14 OLED",
            description="Premium ultrabook with 14-inch 2.8K OLED display, Intel Core Ultra 7, and 75Wh battery.",
            price=84990.00,
            currency="INR",
            category="laptops",
            attributes={
                "brand": "ASUS",
                "processor": "Intel Core Ultra 7 155H",
                "ram_gb": 16,
                "storage_gb": 512,
                "storage_type": "SSD",
                "gpu": "Intel Arc Graphics",
                "operating_system": "Windows 11",
                "display_size_inches": 14.0,
                "battery_life_hours": 14,
                "weight_kg": 1.28,
            },
            stock_quantity=7,
        ),
        Product(
            id="msi-raider-ge78",
            name="MSI Raider GE78 HX",
            description="High-end gaming laptop with 17-inch QHD+ 240Hz display, Intel Core i9, and RTX 4080 GPU.",
            price=189990.00,
            currency="INR",
            category="laptops",
            attributes={
                "brand": "MSI",
                "processor": "Intel Core i9-14900HX",
                "ram_gb": 32,
                "storage_gb": 2048,
                "storage_type": "SSD",
                "gpu": "NVIDIA GeForce RTX 4080",
                "operating_system": "Windows 11",
                "display_size_inches": 17.0,
                "battery_life_hours": 5,
                "weight_kg": 3.00,
            },
            stock_quantity=2,
        ),

        # ── SMARTPHONES (10) ────────────────────────────────────────────
        Product(
            id="redmi-9a",
            name="Redmi 9A",
            description="Entry-level smartphone with 6.53-inch display and solid battery life at a very affordable price.",
            price=7499.00,
            currency="INR",
            category="smartphones",
            attributes={
                "brand": "Redmi",
                "ram_gb": 2,
                "storage_gb": 32,
                "camera_mp": 13,
                "battery_mah": 5000,
                "display_size_inches": 6.53,
                "processor": "MediaTek Helio G25",
                "5g": False,
                "operating_system": "Android 10",
            },
            stock_quantity=60,
        ),
        Product(
            id="samsung-galaxy-a15",
            name="Samsung Galaxy A15",
            description="Budget smartphone with 6.5-inch Super AMOLED display and 5000mAh battery.",
            price=14999.00,
            currency="INR",
            category="smartphones",
            attributes={
                "brand": "Samsung",
                "ram_gb": 4,
                "storage_gb": 128,
                "camera_mp": 50,
                "battery_mah": 5000,
                "display_size_inches": 6.5,
                "processor": "MediaTek Helio G99",
                "5g": False,
                "operating_system": "Android 14",
            },
            stock_quantity=40,
        ),
        Product(
            id="redmi-note-13",
            name="Redmi Note 13",
            description="Value smartphone with 120Hz AMOLED display, 108MP camera, and 5000mAh battery.",
            price=16999.00,
            currency="INR",
            category="smartphones",
            attributes={
                "brand": "Xiaomi",
                "ram_gb": 6,
                "storage_gb": 128,
                "camera_mp": 108,
                "battery_mah": 5000,
                "display_size_inches": 6.67,
                "processor": "Snapdragon 685",
                "5g": False,
                "operating_system": "Android 13",
            },
            stock_quantity=35,
        ),
        Product(
            id="realme-narzo-70",
            name="Realme Narzo 70",
            description="Performance-focused budget phone with Dimensity 7050, 120Hz display, and 5000mAh battery.",
            price=17999.00,
            currency="INR",
            category="smartphones",
            attributes={
                "brand": "Realme",
                "ram_gb": 6,
                "storage_gb": 128,
                "camera_mp": 50,
                "battery_mah": 5000,
                "display_size_inches": 6.72,
                "processor": "MediaTek Dimensity 7050",
                "5g": True,
                "operating_system": "Android 14",
            },
            stock_quantity=30,
        ),
        Product(
            id="samsung-galaxy-m34",
            name="Samsung Galaxy M34",
            description="Mid-range smartphone with 6000mAh battery, 120Hz AMOLED, and 50MP OIS camera.",
            price=19999.00,
            currency="INR",
            category="smartphones",
            attributes={
                "brand": "Samsung",
                "ram_gb": 6,
                "storage_gb": 128,
                "camera_mp": 50,
                "battery_mah": 6000,
                "display_size_inches": 6.5,
                "processor": "Exynos 1280",
                "5g": True,
                "operating_system": "Android 14",
            },
            stock_quantity=25,
        ),
        Product(
            id="oneplus-nord-ce4",
            name="OnePlus Nord CE4",
            description="Sleek mid-range phone with Snapdragon 7 Gen 3, 100W SUPERVOOC charging, and 50MP Sony sensor.",
            price=24999.00,
            currency="INR",
            category="smartphones",
            attributes={
                "brand": "OnePlus",
                "ram_gb": 8,
                "storage_gb": 128,
                "camera_mp": 50,
                "battery_mah": 5500,
                "display_size_inches": 6.7,
                "processor": "Snapdragon 7 Gen 3",
                "5g": True,
                "operating_system": "Android 14",
            },
            stock_quantity=20,
        ),
        Product(
            id="google-pixel-7a",
            name="Google Pixel 7a",
            description="Google's best-value phone with Tensor G2, flagship camera, and 7 years of updates.",
            price=31999.00,
            currency="INR",
            category="smartphones",
            attributes={
                "brand": "Google",
                "ram_gb": 8,
                "storage_gb": 128,
                "camera_mp": 64,
                "battery_mah": 4385,
                "display_size_inches": 6.1,
                "processor": "Google Tensor G2",
                "5g": True,
                "operating_system": "Android 14",
            },
            stock_quantity=12,
        ),
        Product(
            id="samsung-galaxy-s23-fe",
            name="Samsung Galaxy S23 FE",
            description="Fan Edition flagship with 50MP OIS camera, 120Hz AMOLED, and IP68 water resistance.",
            price=39999.00,
            currency="INR",
            category="smartphones",
            attributes={
                "brand": "Samsung",
                "ram_gb": 8,
                "storage_gb": 128,
                "camera_mp": 50,
                "battery_mah": 4500,
                "display_size_inches": 6.4,
                "processor": "Exynos 2200",
                "5g": True,
                "operating_system": "Android 14",
            },
            stock_quantity=10,
        ),
        Product(
            id="iphone-se-2022",
            name="Apple iPhone SE 2022",
            description="Compact iPhone with A15 Bionic chip, 4.7-inch Retina HD display, and Touch ID.",
            price=49900.00,
            currency="INR",
            category="smartphones",
            attributes={
                "brand": "Apple",
                "ram_gb": 4,
                "storage_gb": 64,
                "camera_mp": 12,
                "battery_mah": 2018,
                "display_size_inches": 4.7,
                "processor": "Apple A15 Bionic",
                "5g": True,
                "operating_system": "iOS 17",
            },
            stock_quantity=8,
        ),
        Product(
            id="oneplus-12r",
            name="OnePlus 12R",
            description="Flagship killer with Snapdragon 8 Gen 2, 100W charging, and 50MP Sony IMX890 camera.",
            price=39999.00,
            currency="INR",
            category="smartphones",
            attributes={
                "brand": "OnePlus",
                "ram_gb": 8,
                "storage_gb": 256,
                "camera_mp": 50,
                "battery_mah": 5500,
                "display_size_inches": 6.78,
                "processor": "Snapdragon 8 Gen 2",
                "5g": True,
                "operating_system": "Android 14",
            },
            stock_quantity=9,
        ),
        Product(
            id="samsung-galaxy-s24",
            name="Samsung Galaxy S24",
            description="Compact flagship with Galaxy AI, 50MP camera, titanium frame, and 7 years of updates.",
            price=64999.00,
            currency="INR",
            category="smartphones",
            attributes={
                "brand": "Samsung",
                "ram_gb": 8,
                "storage_gb": 256,
                "camera_mp": 50,
                "battery_mah": 4000,
                "display_size_inches": 6.2,
                "processor": "Exynos 2400",
                "5g": True,
                "operating_system": "Android 14",
            },
            stock_quantity=6,
        ),
        Product(
            id="google-pixel-8a",
            name="Google Pixel 8a",
            description="Clean Android with Google Tensor G3, exceptional camera, and 7 years of software updates.",
            price=47999.00,
            currency="INR",
            category="smartphones",
            attributes={
                "brand": "Google",
                "ram_gb": 8,
                "storage_gb": 128,
                "camera_mp": 64,
                "battery_mah": 4492,
                "display_size_inches": 6.1,
                "processor": "Google Tensor G3",
                "5g": True,
                "operating_system": "Android 14",
            },
            stock_quantity=12,
        ),
        Product(
            id="iqoo-neo-9-pro",
            name="iQOO Neo 9 Pro",
            description="Flagship performance with Snapdragon 8 Gen 2, 120W fast charging, and a 144Hz AMOLED display.",
            price=39999.00,
            currency="INR",
            category="smartphones",
            attributes={
                "brand": "iQOO",
                "ram_gb": 12,
                "storage_gb": 256,
                "camera_mp": 50,
                "battery_mah": 5160,
                "display_size_inches": 6.78,
                "processor": "Snapdragon 8 Gen 2",
                "5g": True,
                "operating_system": "Android 14",
            },
            stock_quantity=15,
        ),
        Product(
            id="apple-iphone-15",
            name="Apple iPhone 15",
            description="A16 Bionic, Dynamic Island, 48MP main camera, and USB-C in a light aluminium body.",
            price=69999.00,
            currency="INR",
            category="smartphones",
            attributes={
                "brand": "Apple",
                "ram_gb": 6,
                "storage_gb": 128,
                "camera_mp": 48,
                "battery_mah": 3349,
                "display_size_inches": 6.1,
                "processor": "Apple A16 Bionic",
                "5g": True,
                "operating_system": "iOS 17",
            },
            stock_quantity=8,
        ),
        Product(
            id="samsung-galaxy-s24-ultra",
            name="Samsung Galaxy S24 Ultra",
            description="Ultimate flagship with S Pen, 200MP camera, titanium frame, and Galaxy AI.",
            price=129999.00,
            currency="INR",
            category="smartphones",
            attributes={
                "brand": "Samsung",
                "ram_gb": 12,
                "storage_gb": 256,
                "camera_mp": 200,
                "battery_mah": 5000,
                "display_size_inches": 6.8,
                "processor": "Snapdragon 8 Gen 3",
                "5g": True,
                "operating_system": "Android 14",
                "s_pen": True,
            },
            stock_quantity=4,
        ),

        # ── SMARTWATCHES (6) ────────────────────────────────────────────
        Product(
            id="redmi-watch-3",
            name="Redmi Watch 3",
            description="Affordable smartwatch with 1.75-inch AMOLED display, GPS, and 14-day battery life.",
            price=3499.00,
            currency="INR",
            category="smartwatches",
            attributes={
                "brand": "Xiaomi",
                "display_size_inches": 1.75,
                "display_type": "AMOLED",
                "battery_life_days": 14,
                "water_resistant": True,
                "gps": True,
                "heart_rate_monitor": True,
                "blood_oxygen_monitor": True,
                "nfc": False,
            },
            stock_quantity=30,
        ),
        Product(
            id="noise-colorfit-pro-5",
            name="Noise Colorfit Pro 5",
            description="Feature-rich smartwatch with 1.85-inch AMOLED, Bluetooth calling, and 100+ watch faces.",
            price=4999.00,
            currency="INR",
            category="smartwatches",
            attributes={
                "brand": "Noise",
                "display_size_inches": 1.85,
                "display_type": "AMOLED",
                "battery_life_days": 7,
                "water_resistant": True,
                "gps": False,
                "heart_rate_monitor": True,
                "blood_oxygen_monitor": True,
                "nfc": False,
            },
            stock_quantity=25,
        ),
        Product(
            id="samsung-galaxy-fit-3",
            name="Samsung Galaxy Fit 3",
            description="Slim fitness band with 1.6-inch AMOLED, 13-day battery, and advanced sleep tracking.",
            price=5999.00,
            currency="INR",
            category="smartwatches",
            attributes={
                "brand": "Samsung",
                "display_size_inches": 1.6,
                "display_type": "AMOLED",
                "battery_life_days": 13,
                "water_resistant": True,
                "gps": True,
                "heart_rate_monitor": True,
                "blood_oxygen_monitor": True,
                "nfc": False,
            },
            stock_quantity=18,
        ),
        Product(
            id="amazfit-gtr-4",
            name="Amazfit GTR 4",
            description="Premium smartwatch with 1.43-inch AMOLED, dual-band GPS, and 24-day battery life.",
            price=16999.00,
            currency="INR",
            category="smartwatches",
            attributes={
                "brand": "Amazfit",
                "display_size_inches": 1.43,
                "display_type": "AMOLED",
                "battery_life_days": 24,
                "water_resistant": True,
                "gps": True,
                "heart_rate_monitor": True,
                "blood_oxygen_monitor": True,
                "nfc": False,
            },
            stock_quantity=10,
        ),
        Product(
            id="apple-watch-se-2",
            name="Apple Watch SE 2",
            description="Entry-level Apple Watch with S8 chip, crash detection, and deep iPhone integration.",
            price=29900.00,
            currency="INR",
            category="smartwatches",
            attributes={
                "brand": "Apple",
                "display_size_inches": 1.78,
                "display_type": "OLED",
                "battery_life_days": 2,
                "water_resistant": True,
                "gps": True,
                "heart_rate_monitor": True,
                "blood_oxygen_monitor": False,
                "nfc": True,
            },
            stock_quantity=7,
        ),
        Product(
            id="samsung-galaxy-watch-6",
            name="Samsung Galaxy Watch 6",
            description="Premium smartwatch with Wear OS, sapphire crystal, bioactive sensor, and sleep coaching.",
            price=27999.00,
            currency="INR",
            category="smartwatches",
            attributes={
                "brand": "Samsung",
                "display_size_inches": 1.47,
                "display_type": "AMOLED",
                "battery_life_days": 2,
                "water_resistant": True,
                "gps": True,
                "heart_rate_monitor": True,
                "blood_oxygen_monitor": True,
                "nfc": True,
            },
            stock_quantity=5,
        ),

        # ── TABLETS (5) ─────────────────────────────────────────────────
        Product(
            id="samsung-galaxy-tab-a9",
            name="Samsung Galaxy Tab A9",
            description="Compact 8.7-inch tablet with MediaTek Helio G99, Dolby Atmos, and expandable storage.",
            price=14999.00,
            currency="INR",
            category="tablets",
            attributes={
                "brand": "Samsung",
                "display_size_inches": 8.7,
                "resolution": "WXGA",
                "ram_gb": 4,
                "storage_gb": 64,
                "processor": "MediaTek Helio G99",
                "battery_mah": 5100,
                "operating_system": "Android 14",
                "stylus_support": False,
            },
            stock_quantity=20,
        ),
        Product(
            id="lenovo-tab-p12",
            name="Lenovo Tab P12",
            description="12.7-inch multimedia tablet with 2K display, JBL quad speakers, and MediaTek Dimensity 7050.",
            price=26999.00,
            currency="INR",
            category="tablets",
            attributes={
                "brand": "Lenovo",
                "display_size_inches": 12.7,
                "resolution": "2K",
                "ram_gb": 8,
                "storage_gb": 256,
                "processor": "MediaTek Dimensity 7050",
                "battery_mah": 10200,
                "operating_system": "Android 13",
                "stylus_support": True,
            },
            stock_quantity=12,
        ),
        Product(
            id="samsung-galaxy-tab-s9-fe",
            name="Samsung Galaxy Tab S9 FE",
            description="Mid-range tablet with 10.9-inch display, S Pen included, IP68 water resistance, and Exynos 1380.",
            price=32999.00,
            currency="INR",
            category="tablets",
            attributes={
                "brand": "Samsung",
                "display_size_inches": 10.9,
                "resolution": "2K",
                "ram_gb": 6,
                "storage_gb": 128,
                "processor": "Exynos 1380",
                "battery_mah": 8000,
                "operating_system": "Android 13",
                "stylus_support": True,
            },
            stock_quantity=10,
        ),
        Product(
            id="ipad-10th-gen",
            name="Apple iPad 10th Gen",
            description="Versatile 10.9-inch iPad with A14 Bionic, Touch ID, and support for Apple Pencil.",
            price=44900.00,
            currency="INR",
            category="tablets",
            attributes={
                "brand": "Apple",
                "display_size_inches": 10.9,
                "resolution": "Liquid Retina",
                "ram_gb": 4,
                "storage_gb": 64,
                "processor": "Apple A14 Bionic",
                "battery_mah": 8686,
                "operating_system": "iPadOS 17",
                "stylus_support": True,
            },
            stock_quantity=8,
        ),
        Product(
            id="ipad-pro-11-m2",
            name="Apple iPad Pro 11 M2",
            description="Pro-grade tablet with M2 chip, 11-inch Liquid Retina XDR display, and Thunderbolt port.",
            price=89900.00,
            currency="INR",
            category="tablets",
            attributes={
                "brand": "Apple",
                "display_size_inches": 11.0,
                "resolution": "Liquid Retina XDR",
                "ram_gb": 8,
                "storage_gb": 256,
                "processor": "Apple M2",
                "battery_mah": 7538,
                "operating_system": "iPadOS 17",
                "stylus_support": True,
            },
            stock_quantity=4,
        ),

        # ── TVs (6) ─────────────────────────────────────────────────────
        Product(
            id="xiaomi-smart-tv-43",
            name="Xiaomi Smart TV 43",
            description="43-inch Full HD Android TV with PatchWall, Dolby Audio, and Chromecast built-in.",
            price=22999.00,
            currency="INR",
            category="tvs",
            attributes={
                "brand": "Xiaomi",
                "screen_size_inches": 43,
                "resolution": "Full HD",
                "display_type": "LED",
                "smart_tv": True,
                "refresh_rate_hz": 60,
                "hdr": False,
                "operating_system": "Android TV",
                "hdmi_ports": 3,
            },
            stock_quantity=15,
        ),
        Product(
            id="redmi-smart-tv-50",
            name="Redmi Smart TV 50",
            description="50-inch 4K UHD smart TV with Vivid Picture Engine, Dolby Vision, and 30W speakers.",
            price=32999.00,
            currency="INR",
            category="tvs",
            attributes={
                "brand": "Xiaomi",
                "screen_size_inches": 50,
                "resolution": "4K UHD",
                "display_type": "LED",
                "smart_tv": True,
                "refresh_rate_hz": 60,
                "hdr": True,
                "operating_system": "Android TV",
                "hdmi_ports": 3,
            },
            stock_quantity=12,
        ),
        Product(
            id="hisense-55a6k",
            name="Hisense 55A6K",
            description="55-inch 4K UHD TV with Dolby Vision, Game Mode, and VIDAA smart platform.",
            price=37999.00,
            currency="INR",
            category="tvs",
            attributes={
                "brand": "Hisense",
                "screen_size_inches": 55,
                "resolution": "4K UHD",
                "display_type": "LED",
                "smart_tv": True,
                "refresh_rate_hz": 60,
                "hdr": True,
                "operating_system": "VIDAA",
                "hdmi_ports": 3,
            },
            stock_quantity=8,
        ),
        Product(
            id="samsung-crystal-55",
            name="Samsung Crystal 4K 55",
            description="55-inch Crystal 4K UHD TV with PurColor, HDR10+, and Tizen smart OS.",
            price=45999.00,
            currency="INR",
            category="tvs",
            attributes={
                "brand": "Samsung",
                "screen_size_inches": 55,
                "resolution": "4K UHD",
                "display_type": "LED",
                "smart_tv": True,
                "refresh_rate_hz": 60,
                "hdr": True,
                "operating_system": "Tizen",
                "hdmi_ports": 3,
            },
            stock_quantity=7,
        ),
        Product(
            id="sony-bravia-55",
            name="Sony BRAVIA 55",
            description="55-inch 4K LED TV with X1 processor, Dolby Vision & Atmos, and Google TV.",
            price=64999.00,
            currency="INR",
            category="tvs",
            attributes={
                "brand": "Sony",
                "screen_size_inches": 55,
                "resolution": "4K UHD",
                "display_type": "LED",
                "smart_tv": True,
                "refresh_rate_hz": 60,
                "hdr": True,
                "operating_system": "Google TV",
                "hdmi_ports": 4,
            },
            stock_quantity=5,
        ),
        Product(
            id="lg-oled55b3",
            name="LG OLED55B3",
            description="55-inch OLED TV with self-lit pixels, Dolby Vision IQ, α9 Gen6 AI processor, and webOS 23.",
            price=109999.00,
            currency="INR",
            category="tvs",
            attributes={
                "brand": "LG",
                "screen_size_inches": 55,
                "resolution": "4K OLED",
                "display_type": "OLED",
                "smart_tv": True,
                "refresh_rate_hz": 120,
                "hdr": True,
                "operating_system": "webOS 23",
                "hdmi_ports": 4,
            },
            stock_quantity=3,
        ),

        # ── SPEAKERS (5) ────────────────────────────────────────────────
        Product(
            id="jbl-go-3",
            name="JBL Go 3",
            description="Ultra-portable Bluetooth speaker with IP67 waterproof design and JBL Pro Sound.",
            price=2499.00,
            currency="INR",
            category="speakers",
            attributes={
                "brand": "JBL",
                "type": "portable",
                "battery_life_hours": 5,
                "water_resistant": True,
                "bluetooth_version": "5.1",
                "power_output_watts": 4,
                "wireless": True,
                "smart_speaker": False,
            },
            stock_quantity=50,
        ),
        Product(
            id="sony-srs-xb100",
            name="Sony SRS-XB100",
            description="Compact wireless speaker with EXTRA BASS, IP67 waterproof, and 16-hour battery life.",
            price=3990.00,
            currency="INR",
            category="speakers",
            attributes={
                "brand": "Sony",
                "type": "portable",
                "battery_life_hours": 16,
                "water_resistant": True,
                "bluetooth_version": "5.2",
                "power_output_watts": 5,
                "wireless": True,
                "smart_speaker": False,
            },
            stock_quantity=35,
        ),
        Product(
            id="jbl-flip-6",
            name="JBL Flip 6",
            description="Portable Bluetooth speaker with powerful JBL Pro Sound, IP67 waterproof, and 12-hour battery.",
            price=9999.00,
            currency="INR",
            category="speakers",
            attributes={
                "brand": "JBL",
                "type": "portable",
                "battery_life_hours": 12,
                "water_resistant": True,
                "bluetooth_version": "5.1",
                "power_output_watts": 20,
                "wireless": True,
                "smart_speaker": False,
            },
            stock_quantity=20,
        ),
        Product(
            id="bose-soundlink-flex",
            name="Bose SoundLink Flex",
            description="Premium portable speaker with PositionIQ, IP67 waterproof, and deep bass.",
            price=13900.00,
            currency="INR",
            category="speakers",
            attributes={
                "brand": "Bose",
                "type": "portable",
                "battery_life_hours": 12,
                "water_resistant": True,
                "bluetooth_version": "5.1",
                "power_output_watts": 0,
                "wireless": True,
                "smart_speaker": False,
            },
            stock_quantity=10,
        ),
        Product(
            id="marshall-stanmore-iii",
            name="Marshall Stanmore III",
            description="Iconic home speaker with True Stereophonic sound, multi-host, and classic Marshall design.",
            price=37999.00,
            currency="INR",
            category="speakers",
            attributes={
                "brand": "Marshall",
                "type": "home",
                "battery_life_hours": 0,
                "water_resistant": False,
                "bluetooth_version": "5.2",
                "power_output_watts": 80,
                "wireless": True,
                "smart_speaker": False,
            },
            stock_quantity=4,
        ),

        # ── CAMERAS (5) ─────────────────────────────────────────────────
        Product(
            id="canon-eos-1500d",
            name="Canon EOS 1500D",
            description="Entry-level DSLR with 24.1MP APS-C sensor, Full HD video, and built-in Wi-Fi.",
            price=36995.00,
            currency="INR",
            category="cameras",
            attributes={
                "brand": "Canon",
                "type": "DSLR",
                "sensor_mp": 24.1,
                "sensor_size": "APS-C",
                "video_resolution": "1080p",
                "iso_range": "100-6400",
                "autofocus_points": 9,
                "image_stabilization": False,
                "wifi": True,
                "weight_grams": 475,
            },
            stock_quantity=8,
        ),
        Product(
            id="nikon-d5600",
            name="Nikon D5600",
            description="Versatile DSLR with 24.2MP CMOS sensor, 39-point AF, Bluetooth, and time-lapse recording.",
            price=46995.00,
            currency="INR",
            category="cameras",
            attributes={
                "brand": "Nikon",
                "type": "DSLR",
                "sensor_mp": 24.2,
                "sensor_size": "APS-C",
                "video_resolution": "1080p",
                "iso_range": "100-25600",
                "autofocus_points": 39,
                "image_stabilization": False,
                "wifi": True,
                "weight_grams": 465,
            },
            stock_quantity=6,
        ),
        Product(
            id="canon-eos-m50-mark-ii",
            name="Canon EOS M50 Mark II",
            description="Compact mirrorless camera with 24.1MP sensor, 4K video, and Dual Pixel CMOS AF.",
            price=54995.00,
            currency="INR",
            category="cameras",
            attributes={
                "brand": "Canon",
                "type": "mirrorless",
                "sensor_mp": 24.1,
                "sensor_size": "APS-C",
                "video_resolution": "4K",
                "iso_range": "100-25600",
                "autofocus_points": 143,
                "image_stabilization": False,
                "wifi": True,
                "weight_grams": 387,
            },
            stock_quantity=5,
        ),
        Product(
            id="sony-a6400",
            name="Sony A6400",
            description="Popular mirrorless camera with 24.2MP sensor, real-time Eye AF, 4K HDR, and flip screen.",
            price=74990.00,
            currency="INR",
            category="cameras",
            attributes={
                "brand": "Sony",
                "type": "mirrorless",
                "sensor_mp": 24.2,
                "sensor_size": "APS-C",
                "video_resolution": "4K",
                "iso_range": "100-32000",
                "autofocus_points": 425,
                "image_stabilization": False,
                "wifi": True,
                "weight_grams": 403,
            },
            stock_quantity=4,
        ),
        Product(
            id="fujifilm-x-t30-ii",
            name="Fujifilm X-T30 II",
            description="Retro-styled mirrorless with 26.1MP X-Trans sensor, 4K video, and Fujifilm color science.",
            price=84999.00,
            currency="INR",
            category="cameras",
            attributes={
                "brand": "Fujifilm",
                "type": "mirrorless",
                "sensor_mp": 26.1,
                "sensor_size": "APS-C",
                "video_resolution": "4K",
                "iso_range": "160-12800",
                "autofocus_points": 425,
                "image_stabilization": False,
                "wifi": True,
                "weight_grams": 378,
            },
            stock_quantity=3,
        ),
        Product(
            id="gopro-hero-11",
            name="GoPro Hero 11 Black",
            description="Rugged waterproof action camera with 5.3K video, HyperSmooth stabilization, and 27MP photos.",
            price=14999.00,
            currency="INR",
            category="cameras",
            attributes={
                "brand": "GoPro",
                "type": "action",
                "sensor_mp": 27.0,
                "sensor_size": "1/1.9-inch",
                "video_resolution": "5.3K",
                "iso_range": "100-6400",
                "autofocus_points": 0,
                "image_stabilization": True,
                "wifi": True,
                "weight_grams": 153,
            },
            stock_quantity=12,
        ),
        Product(
            id="canon-eos-r50",
            name="Canon EOS R50",
            description="Compact mirrorless with 24.2MP APS-C sensor, 4K video, and Dual Pixel CMOS AF II.",
            price=59999.00,
            currency="INR",
            category="cameras",
            attributes={
                "brand": "Canon",
                "type": "mirrorless",
                "sensor_mp": 24.2,
                "sensor_size": "APS-C",
                "video_resolution": "4K",
                "iso_range": "100-32000",
                "autofocus_points": 651,
                "image_stabilization": False,
                "wifi": True,
                "weight_grams": 375,
            },
            stock_quantity=9,
        ),
        Product(
            id="sony-a7-iv",
            name="Sony Alpha A7 IV",
            description="Full-frame mirrorless with 33MP sensor, 10-bit 4K60 video, and fast hybrid autofocus for professionals.",
            price=189990.00,
            currency="INR",
            category="cameras",
            attributes={
                "brand": "Sony",
                "type": "mirrorless",
                "sensor_mp": 33.0,
                "sensor_size": "Full-Frame",
                "video_resolution": "4K",
                "iso_range": "50-204800",
                "autofocus_points": 759,
                "image_stabilization": True,
                "wifi": True,
                "weight_grams": 658,
            },
            stock_quantity=4,
        ),

        # ── KEYBOARDS (5) ───────────────────────────────────────────────
        Product(
            id="cosmic-byte-kb-c45",
            name="Cosmic Byte CB-GK-18",
            description="Budget mechanical keyboard with RGB backlighting, hot-swappable switches, and metal build.",
            price=1999.00,
            currency="INR",
            category="keyboards",
            attributes={
                "brand": "Cosmic Byte",
                "type": "mechanical",
                "wireless": False,
                "switch_type": "Outemu Blue",
                "rgb": True,
                "hot_swappable": True,
                "layout": "TKL",
                "backlight": "RGB",
            },
            stock_quantity=40,
        ),
        Product(
            id="redgear-shadow-amulet",
            name="Redgear Shadow Amulet",
            description="Mechanical gaming keyboard with Outemu Blue switches, LED modes, and Windows key lock.",
            price=2499.00,
            currency="INR",
            category="keyboards",
            attributes={
                "brand": "Redgear",
                "type": "mechanical",
                "wireless": False,
                "switch_type": "Outemu Blue",
                "rgb": True,
                "hot_swappable": False,
                "layout": "Full-size",
                "backlight": "RGB",
            },
            stock_quantity=35,
        ),
        Product(
            id="logitech-mk270",
            name="Logitech MK270",
            description="Wireless keyboard and mouse combo with 10m range, quiet keys, and 24-month battery life.",
            price=1795.00,
            currency="INR",
            category="keyboards",
            attributes={
                "brand": "Logitech",
                "type": "membrane",
                "wireless": True,
                "switch_type": "Membrane",
                "rgb": False,
                "hot_swappable": False,
                "layout": "Full-size",
                "backlight": "None",
            },
            stock_quantity=50,
        ),
        Product(
            id="keychron-k2",
            name="Keychron K2",
            description="Wireless mechanical keyboard with Gateron switches, Mac/Windows compatibility, and 75% layout.",
            price=7499.00,
            currency="INR",
            category="keyboards",
            attributes={
                "brand": "Keychron",
                "type": "mechanical",
                "wireless": True,
                "switch_type": "Gateron Brown",
                "rgb": True,
                "hot_swappable": False,
                "layout": "75%",
                "backlight": "RGB",
            },
            stock_quantity=10,
        ),
        Product(
            id="razer-blackwidow-v4",
            name="Razer BlackWidow V4",
            description="Premium wireless mechanical keyboard with Razer Green switches, aluminum build, and magnetic wrist rest.",
            price=19999.00,
            currency="INR",
            category="keyboards",
            attributes={
                "brand": "Razer",
                "type": "mechanical",
                "wireless": True,
                "switch_type": "Razer Green",
                "rgb": True,
                "hot_swappable": False,
                "layout": "Full-size",
                "backlight": "Per-key RGB",
            },
            stock_quantity=4,
        ),

        # ── MICE (5) ────────────────────────────────────────────────────
        Product(
            id="logitech-m185",
            name="Logitech M185",
            description="Reliable wireless mouse with 12-month battery life, nano receiver, and 1000 DPI sensor.",
            price=795.00,
            currency="INR",
            category="mice",
            attributes={
                "brand": "Logitech",
                "wireless": True,
                "dpi": 1000,
                "gaming": False,
                "ergonomic": False,
                "rgb": False,
                "battery_life_months": 12,
                "sensor_type": "Optical",
                "buttons": 3,
            },
            stock_quantity=60,
        ),
        Product(
            id="redgear-wireless-pro",
            name="Redgear Wireless Pro",
            description="Ergonomic wireless mouse with 4000 DPI sensor, rechargeable battery, and silent clicks.",
            price=1299.00,
            currency="INR",
            category="mice",
            attributes={
                "brand": "Redgear",
                "wireless": True,
                "dpi": 4000,
                "gaming": False,
                "ergonomic": True,
                "rgb": True,
                "battery_life_months": 1,
                "sensor_type": "Optical",
                "buttons": 6,
            },
            stock_quantity=40,
        ),
        Product(
            id="logitech-g102",
            name="Logitech G102",
            description="Popular wired gaming mouse with 8000 DPI sensor, RGB lighting, and lightweight design.",
            price=1595.00,
            currency="INR",
            category="mice",
            attributes={
                "brand": "Logitech",
                "wireless": False,
                "dpi": 8000,
                "gaming": True,
                "ergonomic": False,
                "rgb": True,
                "battery_life_months": 0,
                "sensor_type": "Optical",
                "buttons": 6,
            },
            stock_quantity=35,
        ),
        Product(
            id="razer-deathadder-v3",
            name="Razer DeathAdder V3",
            description="Ergonomic wired gaming mouse with Focus Pro 30K sensor, 63g ultralight, and 90-hour battery.",
            price=6999.00,
            currency="INR",
            category="mice",
            attributes={
                "brand": "Razer",
                "wireless": False,
                "dpi": 30000,
                "gaming": True,
                "ergonomic": True,
                "rgb": True,
                "battery_life_months": 0,
                "sensor_type": "Focus Pro 30K",
                "buttons": 5,
            },
            stock_quantity=8,
        ),
        Product(
            id="logitech-mx-master-3s",
            name="Logitech MX Master 3S",
            description="Premium wireless mouse with MagSpeed scroll, 8000 DPI track-on-glass sensor, and multi-device support.",
            price=9995.00,
            currency="INR",
            category="mice",
            attributes={
                "brand": "Logitech",
                "wireless": True,
                "dpi": 8000,
                "gaming": False,
                "ergonomic": True,
                "rgb": False,
                "battery_life_months": 3,
                "sensor_type": "Darkfield",
                "buttons": 7,
            },
            stock_quantity=6,
        ),
    ]

    new_count = 0
    for product in products:
        if product.id not in existing_ids:
            db.add(product)
            new_count += 1

    if new_count > 0:
        db.commit()

    total = db.query(Product).count()
    return {"added": new_count, "total": total}
